import { randomUUID } from 'node:crypto';

import {
  extendedCostUnits,
  formatMoney,
  formatQuantity,
  moneyUnits,
  quantityUnits,
} from './purchase-money.js';

/**
 * TASK 14.3 (Wave 1, Part C) — "Compra Directa": posts exactly one
 * `receipt` inventory movement for a single stock-tracked variant, at the
 * one authoritative moment `PurchasingService.recordDirectPurchase`
 * records a direct purchase — the only caller, which invokes this *inside
 * its own transaction*, before inserting its own `direct_purchases` row
 * (see that module's own doc comment; `direct_purchases.inventory_movement_id`
 * is NOT NULL by schema design — a direct purchase can never exist without
 * its companion movement already posted).
 *
 * Deliberately the mirror image of `sale-return.ts`'s `postSaleReturn` —
 * same location resolution, same balance-locking discipline, same
 * audit/outbox shape — with the differences this specific direction
 * requires:
 *
 * - **Movement type**: `receipt` — CORE_DATA_MODEL's own canonical type
 *   for "goods physically arrived," never `opening_balance` (that type is
 *   reserved for the one-time initial stock load a branch does before it
 *   ever transacts — see `InventoryPostingService.required`'s own
 *   allow-list) or `adjustment` (a correction to an already-wrong count,
 *   not a real newly-arrived unit).
 * - **Direction**: quantity is *added* (`destination_location_id` set,
 *   `source_location_id` null) — never throws for "insufficient
 *   inventory" (stock can only go up here), exactly like `postSaleReturn`.
 * - **Cost**: unlike a sale return (which never knows a historical unit
 *   cost), a direct purchase's own commercial record — quantity, unit
 *   cost, currency — is written onto the movement LINE too
 *   (`unit_cost`/`extended_cost`/`currency_code`), so the ledger itself
 *   carries the cost fact, not just `direct_purchases`. Deliberately does
 *   NOT recompute `inventory_balances.average_unit_cost` — that would be
 *   a real weighted-average-cost feature this task never asked for (see
 *   TASK 14.3's own explicit "do not build a formal PO workflow" scope
 *   note; the same restraint applies to costing) — left at whatever it
 *   already was, exactly like every other movement type in this codebase
 *   today.
 * - **Idempotency**: the caller's own `idempotent()` wrapper (via
 *   `PurchasingRepository`) is the sole guard — a retried request with the
 *   same `Idempotency-Key` never re-enters `create()` at all, so this
 *   function is only ever invoked once per genuinely-new direct purchase.
 *   `direct_purchases_movement_uq` (schema-level) is the second, durable
 *   guarantee that a `direct_purchases` row can never double-post the same
 *   movement.
 */

export interface PurchaseReceiptTransaction {
  query(sql: string, values?: readonly unknown[]): Promise<unknown>;
}

export interface PurchaseReceiptContext {
  companyId: string;
  actorId: string;
  correlationId: string;
  timestamp: Date;
}

/** The direct purchase this receipt belongs to — `id` is generated by the
 * caller UP FRONT (before either row is inserted) so the movement's own
 * `reference_id` and the `direct_purchases` row it will shortly insert
 * agree on the same id, mirroring exactly how `postSaleReturn`'s
 * `reference_id`/refund id are the SAME value the caller already holds. */
export interface PurchaseReceiptPurchase {
  id: string;
  branchId: string;
}

export interface PurchaseReceiptItem {
  productVariantId: string;
  quantity: string;
  unitCost: string;
  currencyCode: string;
}

export type PurchaseReceiptErrorCode = 'product_variant_not_found' | 'inventory_location_not_found';

export class PurchaseInventoryPostingError extends Error {
  public constructor(
    public readonly code: PurchaseReceiptErrorCode,
    message: string,
  ) {
    super(message);
    this.name = 'PurchaseInventoryPostingError';
  }
}

interface QueryResult<T> {
  rows: T[];
}
function result<T>(value: unknown): QueryResult<T> {
  return value as QueryResult<T>;
}

interface VariantLookup {
  id: string;
  tracks_inventory: boolean;
  unit_of_measure_code: string;
}

export interface PurchaseReceiptPosted {
  movementId: string;
  balanceId: string;
  previousQuantity: string;
  newQuantity: string;
}

/**
 * Posts the single-line `receipt` movement for [item] at [purchase]'s
 * branch, inside the caller's own transaction. Throws
 * `PurchaseInventoryPostingError('product_variant_not_found')` when the
 * variant does not exist in this company (or does not track inventory —
 * a direct purchase only ever makes sense for a stock-tracked variant;
 * recording one for a non-tracked variant would silently create an
 * `inventory_balances` row nothing else in this codebase ever reads) and
 * `('inventory_location_not_found')` when the branch has no active
 * default location — both roll back the caller's whole transaction, so
 * neither `direct_purchases` nor `inventory_movements` ever ends up with
 * an orphaned row on either side of that failure.
 */
export async function postDirectPurchaseReceipt(
  client: PurchaseReceiptTransaction,
  context: PurchaseReceiptContext,
  purchase: PurchaseReceiptPurchase,
  item: PurchaseReceiptItem,
): Promise<PurchaseReceiptPosted> {
  const variant = result<VariantLookup>(
    await client.query(
      `select id, tracks_inventory, unit_of_measure_code
       from product_variants
       where company_id=$1 and id=$2`,
      [context.companyId, item.productVariantId],
    ),
  ).rows[0];
  if (!variant?.tracks_inventory)
    throw new PurchaseInventoryPostingError(
      'product_variant_not_found',
      'The product variant was not found or does not track inventory.',
    );

  const location = result<{ id: string }>(
    await client.query(
      `select id from inventory_locations
       where company_id=$1 and branch_id=$2 and is_default=true and status='active'`,
      [context.companyId, purchase.branchId],
    ),
  ).rows[0];
  if (location === undefined)
    throw new PurchaseInventoryPostingError(
      'inventory_location_not_found',
      'No active default inventory location is configured for this branch.',
    );

  const qtyUnits = quantityUnits(item.quantity);
  const unitCostUnits = moneyUnits(item.unitCost);
  const extendedUnits = extendedCostUnits(unitCostUnits, qtyUnits);

  const movementId = randomUUID();
  const movementNumber = `IMV-${movementId.replaceAll('-', '').toLowerCase()}`;
  await client.query(
    `insert into inventory_movements
     (id,company_id,branch_id,movement_number,movement_type,status,reference_type,reference_id,
      version,occurred_at,posted_at,posted_by,created_by,created_at,updated_at)
     values ($1,$2,$3,$4,'receipt','posted','direct_purchase',$5,1,$6,$6,$7,$7,$6,$6)`,
    [movementId, context.companyId, purchase.branchId, movementNumber, purchase.id, context.timestamp, context.actorId],
  );

  const balance = result<{ id: string; quantity_on_hand: string; version: string }>(
    await client.query(
      `select id, quantity_on_hand::text, version::text
       from inventory_balances
       where company_id=$1 and branch_id=$2 and inventory_location_id=$3 and product_variant_id=$4
       for update`,
      [context.companyId, purchase.branchId, location.id, variant.id],
    ),
  ).rows[0];

  let balanceId: string;
  let previous: bigint;
  let next: bigint;
  let balanceVersion: bigint;
  if (balance === undefined) {
    balanceId = randomUUID();
    next = qtyUnits;
    previous = 0n;
    balanceVersion = 1n;
    await client.query(
      `insert into inventory_balances
       (id,company_id,branch_id,inventory_location_id,product_variant_id,quantity_on_hand,
        quantity_reserved,quantity_in_transit,average_unit_cost,version,last_movement_id,created_at,updated_at)
       values ($1,$2,$3,$4,$5,$6,0,0,0,1,$7,$8,$8)`,
      [balanceId, context.companyId, purchase.branchId, location.id, variant.id, item.quantity, movementId, context.timestamp],
    );
  } else {
    balanceId = balance.id;
    previous = quantityUnits(balance.quantity_on_hand);
    next = previous + qtyUnits;
    balanceVersion = BigInt(balance.version) + 1n;
    await client.query(
      `update inventory_balances set quantity_on_hand=$2, version=version+1, last_movement_id=$3, updated_at=$4
       where id=$1`,
      [balance.id, formatQuantity(next), movementId, context.timestamp],
    );
  }

  await client.query(
    `insert into inventory_movement_lines
     (id,company_id,inventory_movement_id,line_number,product_variant_id,source_location_id,
      destination_location_id,quantity,unit_of_measure_code,base_quantity,unit_cost,extended_cost,
      currency_code,created_at)
     values ($1,$2,$3,1,$4,null,$5,$6,$7,$6,$8,$9,$10,$11)`,
    [
      randomUUID(),
      context.companyId,
      movementId,
      variant.id,
      location.id,
      item.quantity,
      variant.unit_of_measure_code,
      item.unitCost,
      formatMoney(extendedUnits),
      item.currencyCode,
      context.timestamp,
    ],
  );

  await client.query(
    `insert into audit_log
     (id,company_id,actor_type,actor_id,action,entity_type,entity_id,correlation_id,metadata,occurred_at)
     values ($1,$2,'user',$3,'inventory_movement.posted','inventory_movement',$4,$5,$6::jsonb,$7)`,
    [
      randomUUID(),
      context.companyId,
      context.actorId,
      movementId,
      context.correlationId,
      JSON.stringify({
        movement_number: movementNumber,
        movement_type: 'receipt',
        reference_type: 'direct_purchase',
        reference_id: purchase.id,
        line_count: 1,
      }),
      context.timestamp,
    ],
  );

  await client.query(
    `insert into outbox_events
     (event_id,company_id,branch_id,event_type,schema_version,aggregate_type,
      aggregate_id,aggregate_version,correlation_id,payload,occurred_at,available_at,created_at)
     values ($1,$2,$3,'inventory.movement.created',1,'inventory_movement',$4,1,$5,$6::jsonb,$7,$7,$7)`,
    [
      randomUUID(),
      context.companyId,
      purchase.branchId,
      movementId,
      context.correlationId,
      JSON.stringify({
        company_id: context.companyId,
        branch_id: purchase.branchId,
        movement_id: movementId,
        movement_number: movementNumber,
        movement_type: 'receipt',
        status: 'posted',
        posted_at: context.timestamp.toISOString(),
        actor_id: context.actorId,
        correlation_id: context.correlationId,
        line_count: 1,
        reference_type: 'direct_purchase',
        reference_id: purchase.id,
      }),
      context.timestamp,
    ],
  );
  await client.query(
    `insert into outbox_events
     (event_id,company_id,branch_id,event_type,schema_version,aggregate_type,
      aggregate_id,aggregate_version,correlation_id,payload,occurred_at,available_at,created_at)
     values ($1,$2,$3,'inventory.stock.changed',1,'inventory_balance',$4,$5,$6,$7::jsonb,$8,$8,$8)`,
    [
      randomUUID(),
      context.companyId,
      purchase.branchId,
      balanceId,
      balanceVersion.toString(),
      context.correlationId,
      JSON.stringify({
        company_id: context.companyId,
        branch_id: purchase.branchId,
        balance_id: balanceId,
        inventory_location_id: location.id,
        product_variant_id: variant.id,
        previous_quantity_on_hand: formatQuantity(previous),
        delta_quantity_on_hand: formatQuantity(qtyUnits),
        new_quantity_on_hand: formatQuantity(next),
        movement_id: movementId,
        movement_number: movementNumber,
        occurred_at: context.timestamp.toISOString(),
        correlation_id: context.correlationId,
      }),
      context.timestamp,
    ],
  );

  return {
    movementId,
    balanceId,
    previousQuantity: formatQuantity(previous),
    newQuantity: formatQuantity(next),
  };
}
