import { randomUUID } from 'node:crypto';

import {
  extendedCostUnits,
  formatMoney,
  formatQuantity,
  moneyUnits,
  quantityUnits,
} from './purchase-money.js';

/**
 * TASK 12.2 — the Purchase Order receiving path, the direct sibling of
 * `purchase-receipt.ts`'s `postDirectPurchaseReceipt` (TASK 14.3). Posts
 * exactly one `receipt` inventory movement — but, unlike a direct
 * purchase's single-line movement, this one can carry MULTIPLE lines
 * (one per PO line actually received in this event, in the caller's own
 * order) inside the SAME movement row. `PurchaseOrdersService.
 * receivePurchaseOrder` is the only caller, invoking this inside its own
 * transaction, before updating `purchase_order_lines.received_quantity`
 * and `purchase_orders.status`/`received_at`/`received_by`/
 * `receipt_movement_id`/`version` — all inside that one transaction, so a
 * failure at any point (an invalid variant, a missing default location)
 * rolls every one of these back together, exactly like
 * `postDirectPurchaseReceipt`'s own atomicity guarantee.
 *
 * Deliberately reuses `purchase-money.ts`'s exact scaled-BigInt decimal
 * helpers — never a second, possibly-drifting implementation of the same
 * quantity/money math `postDirectPurchaseReceipt` already established.
 *
 * - **Movement type**: `receipt`, `reference_type='purchase_order'` —
 *   same canonical "goods physically arrived" type direct purchases use,
 *   just with a different `reference_type`/multiple lines.
 * - **Direction**: quantity is always *added* (`destination_location_id`
 *   set, `source_location_id` null) for every line — never throws for
 *   "insufficient inventory," exactly like `postDirectPurchaseReceipt`.
 * - **Cost**: each line's own `unit_cost`/`extended_cost`/`currency_code`
 *   is written onto its own `inventory_movement_lines` row, same as a
 *   direct purchase. Deliberately does NOT recompute `inventory_balances.
 *   average_unit_cost` — out of scope, exactly like `postDirectPurchaseReceipt`.
 * - **Audit/outbox shape**: ONE movement row, ONE audit_log row, and
 *   exactly TWO outbox_events rows total — `inventory.movement.created`
 *   (summarizing the whole movement) and a single `inventory.stock.
 *   changed` event whose payload carries a `lines` array, one entry per
 *   affected balance — deliberately NOT one `inventory.stock.changed`
 *   event per line (that would make an N-line PO receipt emit N+1
 *   outbox rows instead of the fixed pair this task's own spec calls
 *   for: "insert only ONE movement row and ONE pair of audit/outbox rows
 *   summarizing all lines").
 * - **Idempotency**: the caller's own `idempotent()` wrapper is the sole
 *   guard, exactly like direct purchases — a retried request with the
 *   same `Idempotency-Key` never re-enters the receive handler at all.
 */

export interface PurchaseOrderReceiptTransaction {
  query(sql: string, values?: readonly unknown[]): Promise<unknown>;
}

export interface PurchaseOrderReceiptContext {
  companyId: string;
  actorId: string;
  correlationId: string;
  timestamp: Date;
}

/** The purchase order this receipt belongs to — `id` is generated by the
 * caller up front, mirroring `PurchaseReceiptPurchase`'s own established
 * pattern. */
export interface PurchaseOrderReceiptOrder {
  id: string;
  branchId: string;
}

export interface PurchaseOrderReceiptLine {
  productVariantId: string;
  quantity: string;
  unitCost: string;
  currencyCode: string;
}

export type PurchaseOrderReceiptErrorCode =
  | 'product_variant_not_found'
  | 'inventory_location_not_found';

export class PurchaseOrderInventoryPostingError extends Error {
  public constructor(
    public readonly code: PurchaseOrderReceiptErrorCode,
    message: string,
  ) {
    super(message);
    this.name = 'PurchaseOrderInventoryPostingError';
  }
}

interface QueryResult<T> {
  rows: T[];
}
function result<T>(value: unknown): QueryResult<T> {
  return value as QueryResult<T>;
}

interface VariantLookup {
  id: string;
  tracks_inventory: boolean;
  unit_of_measure_code: string;
}

export interface PurchaseOrderReceiptPostedLine {
  productVariantId: string;
  balanceId: string;
  previousQuantity: string;
  newQuantity: string;
}

export interface PurchaseOrderReceiptPosted {
  movementId: string;
  movementNumber: string;
  lines: readonly PurchaseOrderReceiptPostedLine[];
}

/**
 * Posts a single `receipt` movement with one line per entry in [items]
 * (already filtered by the caller to exclude any zero-quantity lines for
 * this event — see `PurchaseOrdersService.receivePurchaseOrder`'s own
 * doc comment), at [order]'s branch, inside the caller's own
 * transaction. Throws `PurchaseOrderInventoryPostingError
 * ('product_variant_not_found')` when a variant does not exist in this
 * company (or does not track inventory) and `('inventory_location_not_found')`
 * when the branch has no active default location — both roll back the
 * caller's whole transaction, exactly like `postDirectPurchaseReceipt`.
 */
export async function postPurchaseOrderReceipt(
  client: PurchaseOrderReceiptTransaction,
  context: PurchaseOrderReceiptContext,
  order: PurchaseOrderReceiptOrder,
  items: readonly PurchaseOrderReceiptLine[],
): Promise<PurchaseOrderReceiptPosted> {
  const location = result<{ id: string }>(
    await client.query(
      `select id from inventory_locations
       where company_id=$1 and branch_id=$2 and is_default=true and status='active'`,
      [context.companyId, order.branchId],
    ),
  ).rows[0];
  if (location === undefined)
    throw new PurchaseOrderInventoryPostingError(
      'inventory_location_not_found',
      'No active default inventory location is configured for this branch.',
    );

  const movementId = randomUUID();
  const movementNumber = `IMV-${movementId.replaceAll('-', '').toLowerCase()}`;
  await client.query(
    `insert into inventory_movements
     (id,company_id,branch_id,movement_number,movement_type,status,reference_type,reference_id,
      version,occurred_at,posted_at,posted_by,created_by,created_at,updated_at)
     values ($1,$2,$3,$4,'receipt','posted','purchase_order',$5,1,$6,$6,$7,$7,$6,$6)`,
    [movementId, context.companyId, order.branchId, movementNumber, order.id, context.timestamp, context.actorId],
  );

  const postedLines: PurchaseOrderReceiptPostedLine[] = [];
  const stockChangeLines: {
    inventory_location_id: string;
    product_variant_id: string;
    balance_id: string;
    balance_version: string;
    previous_quantity_on_hand: string;
    delta_quantity_on_hand: string;
    new_quantity_on_hand: string;
  }[] = [];

  for (const [index, item] of items.entries()) {
    const variant = result<VariantLookup>(
      await client.query(
        `select id, tracks_inventory, unit_of_measure_code
         from product_variants
         where company_id=$1 and id=$2`,
        [context.companyId, item.productVariantId],
      ),
    ).rows[0];
    if (!variant?.tracks_inventory)
      throw new PurchaseOrderInventoryPostingError(
        'product_variant_not_found',
        'The product variant was not found or does not track inventory.',
      );

    const qtyUnits = quantityUnits(item.quantity);
    const unitCostUnits = moneyUnits(item.unitCost);
    const extendedUnits = extendedCostUnits(unitCostUnits, qtyUnits);

    const balance = result<{ id: string; quantity_on_hand: string; version: string }>(
      await client.query(
        `select id, quantity_on_hand::text, version::text
         from inventory_balances
         where company_id=$1 and branch_id=$2 and inventory_location_id=$3 and product_variant_id=$4
         for update`,
        [context.companyId, order.branchId, location.id, variant.id],
      ),
    ).rows[0];

    let balanceId: string;
    let previous: bigint;
    let next: bigint;
    let balanceVersion: bigint;
    if (balance === undefined) {
      balanceId = randomUUID();
      next = qtyUnits;
      previous = 0n;
      balanceVersion = 1n;
      await client.query(
        `insert into inventory_balances
         (id,company_id,branch_id,inventory_location_id,product_variant_id,quantity_on_hand,
          quantity_reserved,quantity_in_transit,average_unit_cost,version,last_movement_id,created_at,updated_at)
         values ($1,$2,$3,$4,$5,$6,0,0,0,1,$7,$8,$8)`,
        [balanceId, context.companyId, order.branchId, location.id, variant.id, item.quantity, movementId, context.timestamp],
      );
    } else {
      balanceId = balance.id;
      previous = quantityUnits(balance.quantity_on_hand);
      next = previous + qtyUnits;
      balanceVersion = BigInt(balance.version) + 1n;
      await client.query(
        `update inventory_balances set quantity_on_hand=$2, version=version+1, last_movement_id=$3, updated_at=$4
         where id=$1`,
        [balance.id, formatQuantity(next), movementId, context.timestamp],
      );
    }

    await client.query(
      `insert into inventory_movement_lines
       (id,company_id,inventory_movement_id,line_number,product_variant_id,source_location_id,
        destination_location_id,quantity,unit_of_measure_code,base_quantity,unit_cost,extended_cost,
        currency_code,created_at)
       values ($1,$2,$3,$4,$5,null,$6,$7,$8,$7,$9,$10,$11,$12)`,
      [
        randomUUID(),
        context.companyId,
        movementId,
        index + 1,
        variant.id,
        location.id,
        item.quantity,
        variant.unit_of_measure_code,
        item.unitCost,
        formatMoney(extendedUnits),
        item.currencyCode,
        context.timestamp,
      ],
    );

    postedLines.push({
      productVariantId: variant.id,
      balanceId,
      previousQuantity: formatQuantity(previous),
      newQuantity: formatQuantity(next),
    });
    stockChangeLines.push({
      inventory_location_id: location.id,
      product_variant_id: variant.id,
      balance_id: balanceId,
      balance_version: balanceVersion.toString(),
      previous_quantity_on_hand: formatQuantity(previous),
      delta_quantity_on_hand: formatQuantity(qtyUnits),
      new_quantity_on_hand: formatQuantity(next),
    });
  }

  await client.query(
    `insert into audit_log
     (id,company_id,actor_type,actor_id,action,entity_type,entity_id,correlation_id,metadata,occurred_at)
     values ($1,$2,'user',$3,'inventory_movement.posted','inventory_movement',$4,$5,$6::jsonb,$7)`,
    [
      randomUUID(),
      context.companyId,
      context.actorId,
      movementId,
      context.correlationId,
      JSON.stringify({
        movement_number: movementNumber,
        movement_type: 'receipt',
        reference_type: 'purchase_order',
        reference_id: order.id,
        line_count: items.length,
      }),
      context.timestamp,
    ],
  );

  await client.query(
    `insert into outbox_events
     (event_id,company_id,branch_id,event_type,schema_version,aggregate_type,
      aggregate_id,aggregate_version,correlation_id,payload,occurred_at,available_at,created_at)
     values ($1,$2,$3,'inventory.movement.created',1,'inventory_movement',$4,1,$5,$6::jsonb,$7,$7,$7)`,
    [
      randomUUID(),
      context.companyId,
      order.branchId,
      movementId,
      context.correlationId,
      JSON.stringify({
        company_id: context.companyId,
        branch_id: order.branchId,
        movement_id: movementId,
        movement_number: movementNumber,
        movement_type: 'receipt',
        status: 'posted',
        posted_at: context.timestamp.toISOString(),
        actor_id: context.actorId,
        correlation_id: context.correlationId,
        line_count: items.length,
        reference_type: 'purchase_order',
        reference_id: order.id,
      }),
      context.timestamp,
    ],
  );
  await client.query(
    `insert into outbox_events
     (event_id,company_id,branch_id,event_type,schema_version,aggregate_type,
      aggregate_id,aggregate_version,correlation_id,payload,occurred_at,available_at,created_at)
     values ($1,$2,$3,'inventory.stock.changed',1,'inventory_movement',$4,1,$5,$6::jsonb,$7,$7,$7)`,
    [
      randomUUID(),
      context.companyId,
      order.branchId,
      movementId,
      context.correlationId,
      JSON.stringify({
        company_id: context.companyId,
        branch_id: order.branchId,
        movement_id: movementId,
        movement_number: movementNumber,
        occurred_at: context.timestamp.toISOString(),
        correlation_id: context.correlationId,
        lines: stockChangeLines,
      }),
      context.timestamp,
    ],
  );

  return { movementId, movementNumber, lines: postedLines };
}
